apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: sync2jira
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/sync2jira/sync2jira@sha256:e091029fcfd63c7a0a4659bc661150bfc7ecd1b5d53cccd81def4e591ff65d30
        name: container-image
        resources: {}
status: {}
