apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sync2jira-up7w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sync2jira-up7w
    app.kubernetes.io/part-of: sync2jira
  name: sync2jira-up7wukzs
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: sync2jira-up7w
    weight: 100
status: {}
