apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sync2jira-up7w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sync2jira-up7w
    app.kubernetes.io/part-of: sync2jira
  name: sync2jira-up7w
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: sync2jira-up7w
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: sync2jira-up7w
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ralphjbean-tenant/sync2jira/sync2jira-up7w@sha256:d9aea8976fe340017ede83acc09d0aa9a7b682750b249a2516f4011936dddd72
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
