apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sync2jira-up7w
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sync2jira-up7w
    app.kubernetes.io/part-of: sync2jira
  name: sync2jira-up7w
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: sync2jira-up7w
status:
  loadBalancer: {}
